### ISSUE TITLE
Suggestion: optional description for items?

### ISSUE THREAD

**Issue by emilyann-RB** [LazyDope/avrae-stuff#11]
I am wondering if there is a way to add the option for a short description to be added to an item in the bag? Even just a statement for any bonuses the item gives if applicable.
It would be helpful for traditional or homebrew items so that members of a campaign would more clearly understand what their group members have -> if that is something a character wants to be known. Thoughts? 
Thanks in advance :)

**Comment by LazyDope** [comment]
Would this not be better solved by a pack?
