### ISSUE TITLE
Delete an XP Entry vs. minus amount

### ISSUE THREAD

**Issue by Stoutman314** [LazyDope/avrae-stuff#16]
Evening, just a simple question.  Doing an audit on my server, and I have some entries in the !xp system; is there a way to delete an entry in the xp log or do you have to just minus the entry out?

Thanks in advance!!!!!

**Comment by LazyDope** [comment]
You can edit the cvar to remove a log entry, but the point of the log is to keep track of all changes, even mistakes, so there's no built-in delete function.

**Comment by Stoutman314** [comment]
Ok, makes sense. Thank you for the reply!!!!!Sent from my iPhoneOn Feb 5, 2024, at 7:08 AM, Byron Pettigrew ***@***.***> wrote:﻿
You can edit the cvar to remove a log entry, but the point of the log is to keep track of all changes, even mistakes, so there's no built-in delete function.
